const D=DATA,$=s=>document.querySelector(s),app=$("#app");
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const links=a=>`<div class="links">${a.map(l=>`<a href="${esc(l.u)}" target="_blank" rel="noopener noreferrer">${esc(l.n)}</a>`).join("")}</div>`;
const ul=(a,c="")=>`<ul class="${c}">${a.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`;
const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
const PAGES=[["detect","Détecter"],["protect","Protéger"],["hack","Comprendre"],["tools","Outils"],["incident","Incident"],["certs","Certifications"],["roadmap","Roadmap"],["learn","Fondamentaux"]];
const SHORT=["bit.ly","tinyurl.com","t.co","goo.gl","is.gd","cutt.ly","ow.ly"],BAD_TLD=["zip","xyz","top","click","work","support","gq","tk"],BRANDS=["paypal","google","microsoft","apple","amazon","facebook","instagram","netflix","bank"],WORDS=["login","verify","secure","update","account","password","signin","auth"];
function analyze(raw){
 let u;try{u=new URL(/^[a-z]+:\/\//i.test(raw)?raw:"https://"+raw)}catch{return null}
 const h=u.hostname.toLowerCase(),parts=h.split("."),root=parts.length>1?parts.slice(-2).join("."):h,f=[];const add=(sev,t)=>f.push({sev,t});
 if(u.protocol!=="https:")add("bad","Pas de HTTPS : les échanges ne bénéficient pas du chiffrement TLS attendu pour un site web moderne.");
 if(/^\d+\.\d+\.\d+\.\d+$/.test(h))add("bad","Adresse IP utilisée comme hôte au lieu d'un nom de domaine.");
 if(h.includes("xn--"))add("bad","Domaine en punycode : peut être utilisé pour des homographes trompeurs.");
 if(raw.includes("@"))add("bad","Caractère @ dans l'URL : peut masquer la destination réelle.");
 if(SHORT.includes(h))add("warn","URL raccourcie : la destination finale n'est pas visible directement.");
 if(BAD_TLD.includes(parts.at(-1)))add("warn","Extension de domaine observée dans de nombreux abus ; ce n'est pas une preuve à elle seule.");
 if(parts.length>4)add("warn","Nombre élevé de sous-domaines.");
 if((root.match(/-/g)||[]).length>1)add("warn","Plusieurs tirets dans le domaine racine.");
 const b=BRANDS.find(x=>h.includes(x)&&root!==x+".com"&&root!==x+".org");
 if(b)add("bad",`Le terme « ${b} » apparaît dans l'hôte sans être le domaine principal (${root}).`);
 if(WORDS.some(w=>u.pathname.toLowerCase().includes(w)))add("warn","Le chemin contient un terme lié à la connexion, à l'authentification ou à une vérification.");
 if(raw.length>100)add("warn","URL longue : caractéristique parfois rencontrée dans des liens de phishing.");
 return{raw,h,root,protocol:u.protocol,port:u.port||"standard",path:u.pathname,f};
}
function urlTools(raw){const e=encodeURIComponent(raw);return[{n:"VirusTotal",u:"https://www.virustotal.com/gui/search/"+e},{n:"URLScan",u:"https://urlscan.io/search/#"+e},{n:"Google Safe Browsing",u:"https://transparencyreport.google.com/safe-browsing/search?url="+e},{n:"PhishTank",u:"https://phishtank.org"}]}
function runCheck(){
 const raw=$("#u").value.trim(),out=$("#res");if(!raw){out.innerHTML=`<p class="note">Saisissez une URL, par exemple https://exemple.com/connexion</p>`;return}
 const a=analyze(raw);if(!a){out.innerHTML=`<p class="note">Cette URL n'est pas valide. Vérifiez sa syntaxe.</p>`;return}
 const bad=a.f.some(x=>x.sev==="bad"),warn=a.f.some(x=>x.sev==="warn"),score=Math.min(100,a.f.reduce((n,x)=>n+(x.sev==="bad"?25:10),0));
 out.innerHTML=`<div class="panel report"><div class="report-head"><div><span class="eyebrow">Analyse locale</span><h3>${esc(a.root)}</h3></div><span class="risk ${bad?"bad":warn?"warn":"ok"}">${bad?"Risque élevé":warn?"À vérifier":"Aucun indicateur local"}</span></div>
 <div class="stats"><div><b>${a.protocol.replace(":","").toUpperCase()}</b><small>protocole</small></div><div><b>${a.f.length}</b><small>indicateurs</small></div><div><b>${score}</b><small>score heuristique</small></div></div>
 ${a.f.length?`<ul class="findings">${a.f.map(x=>`<li class="sev-${x.sev}"><b>${x.sev==="bad"?"Signal fort":"Point d'attention"}</b> — ${esc(x.t)}</li>`).join("")}</ul>`:`<p class="sev-ok"><strong>Aucun indicateur heuristique détecté.</strong></p>`}
 <div class="note"><strong>À retenir :</strong> ceci est une analyse de forme, pas une réputation réelle. Un score faible ne prouve pas qu'un lien est sûr.</div>
 <h3>Vérification externe</h3><p>Pour obtenir une réputation issue de plusieurs sources, ouvrez les services ci-dessous. La version actuelle ne transmet pas automatiquement votre URL.</p>${links(urlTools(raw))}</div>`;
}
function chips(show){const bs=[...app.querySelectorAll(".chip")];bs.forEach(b=>b.onclick=()=>{bs.forEach(x=>x.setAttribute("aria-pressed",x===b));show(+b.dataset.i)});if(bs.length)show(0)}
const R={
 home:()=>`<section class="hero home-hero"><div class="hero-copy"><div class="status-line"><span class="status-dot"></span> CYBER INTELLIGENCE HUB <span class="status-sep">/</span> SYSTEM ONLINE</div><span class="eyebrow">LEARN · DETECT · PROTECT · UNDERSTAND</span><h1>Know the threat.<br><span>Control the risk.</span></h1><p class="lead">CyberHub transforme la cybersécurité en parcours clair : comprendre ce qui se passe, analyser les signaux, choisir le bon outil et savoir quoi faire ensuite.</p><div class="hero-actions"><a class="btn btn-ghost" href="#/roadmap">Start the roadmap <span>↗</span></a><a class="text-link" href="#/tools">Explore tools →</a></div></div><div class="hero-visual"><canvas id="cyber-scene" aria-label="Entité 3D de malware, réseau infecté et signaux de menace"></canvas><div class="scene-label scene-label-a"><span>THREAT ENTITY</span><b>MALWARE // ACTIVE</b></div><div class="scene-label scene-label-b"><span>INFECTION</span><b>CRITICAL SIGNAL</b></div><div class="scene-core"><span>CYBER</span><b>HUB</b></div></div></section>
 <section class="risk-strip"><div><span class="eyebrow">RISK SIGNAL</span><b>Red means attention.</b><small>Le rouge signale le risque, l'alerte ou l'action urgente.</small></div><div class="risk-scale"><span class="r-low"></span><span class="r-mid"></span><span class="r-high"></span><span class="r-critical"></span></div><div class="risk-caption"><span>LOW</span><span>CRITICAL</span></div></section>
 <section class="section"><div class="section-title"><div><span class="eyebrow">MISSION CONTROL</span><h2>Choose your operation</h2></div><span class="section-index">01 / 04</span></div><div class="grid command-grid">${[["detect","01","DETECT","Quelque chose paraît suspect ? Identifiez les signaux, les symptômes et les premières actions."],["protect","02","PROTECT","Renforcez un compte, une machine, un réseau ou un site avec une checklist guidée."],["hack","03","UNDERSTAND","Comprenez les attaques : fonctionnement, impact, détection, prévention et pratique légale."],["certs","04","CERTIFY","Trouvez une certification adaptée à votre niveau et à votre spécialisation."]].map(p=>`<a class="command-card" href="#/${p[0]}"><span class="command-no">${p[1]}</span><div><span class="eyebrow">${p[2]}</span><h3>${p[2]}</h3><p>${p[3]}</p></div><span class="command-arrow">↗</span></a>`).join("")}</div></section>
 <section class="section tools-preview"><div class="section-title"><div><span class="eyebrow">ANALYSIS TOOLKIT</span><h2>From signal to answer</h2></div><a class="text-link" href="#/tools">View all tools →</a></div><div class="grid grid-3"><a class="mini-card cyber-mini" href="#/"><span class="mini-icon">URL</span><b>URL Intelligence</b><small>Heuristics + reputation services for suspicious links.</small></a><a class="mini-card cyber-mini" href="#/tools"><span class="mini-icon">DNS</span><b>Domain Recon</b><small>DNS, certificates, reputation and public intelligence.</small></a><a class="mini-card cyber-mini" href="#/incident"><span class="mini-icon">IR</span><b>Incident Response</b><small>Identify → Isolate → Contain → Recover.</small></a></div></section>
 <section class="section philosophy"><div><span class="eyebrow">THE CYBERHUB METHOD</span><h2>Observe. Understand. Act.</h2></div><div class="method-line"><div><b>01</b><span>Observe</span><small>Find the signal.</small></div><i>→</i><div><b>02</b><span>Understand</span><small>Know the attack.</small></div><i>→</i><div><b>03</b><span>Act</span><small>Reduce the risk.</small></div></div></section>`,
 detect:()=>`<h1>Détecter</h1><p class="lead">Sélectionnez ce que vous observez pour obtenir des signes, des actions immédiates et des outils.</p><div class="chips">${D.detect.map((d,i)=>`<button class="chip" aria-pressed="${i===0}" data-i="${i}">${d.t}</button>`).join("")}</div><div id="out"></div>`,
 protect:()=>`<h1>Protéger</h1><p class="lead">Choisissez un actif. La checklist est sauvegardée localement dans votre navigateur.</p><div class="chips">${D.assets.map((d,i)=>`<button class="chip" aria-pressed="${i===0}" data-i="${i}">${d.t}</button>`).join("")}</div><div id="out"></div>`,
 hack:()=>`<h1>Comprendre les attaques</h1><p class="lead">Comprendre une attaque sans fournir de procédure d'exploitation. Chaque fiche relie fonctionnement → impact → détection → prévention → entraînement autorisé.</p><h2>Types d'acteurs</h2><div class="grid">${D.hackers.map(h=>`<div class="panel"><span class="tag">${h.c}</span><h3>${h.t}</h3><p>${h.d}</p></div>`).join("")}</div><h2>Types d'attaques</h2><div class="chips">${D.attacks.map((d,i)=>`<button class="chip" aria-pressed="${i===0}" data-i="${i}">${d.t}</button>`).join("")}</div><div id="out"></div><h2>Labs autorisés</h2>${links(D.practice)}`,
 tools:()=>`<h1>Tool Finder</h1><p class="lead">Choisissez l'objet à analyser. CyberHub vous indique les familles d'outils et leur rôle.</p><div class="finder-search"><input id="toolq" type="search" placeholder="Rechercher : URL, IP, malware, DNS…" aria-label="Rechercher un outil"></div><div class="chips">${D.finder.map((d,i)=>`<button class="chip" aria-pressed="${i===0}" data-i="${i}">${d.k}</button>`).join("")}</div><div id="out"></div>`,
 incident:()=>`<h1>Réponse à incident</h1><p class="lead">Un guide d'orientation. En entreprise, suivez les procédures internes et l'équipe de sécurité.</p><ol class="flow">${D.ir.map(s=>`<li>${s[0]}</li>`).join("")}</ol><div class="cols">${D.ir.map(s=>`<div class="panel"><span class="eyebrow">ÉTAPE</span><h3>${s[0]}</h3><p>${s[1]}</p></div>`).join("")}</div><div class="cols"><div class="do panel"><h3>À faire</h3>${ul(D.irDo,"do")}</div><div class="dont panel"><h3>À éviter</h3>${ul(D.irDont,"dont")}</div></div>`,
 certs:()=>`<h1>Certifications</h1><p class="lead">Filtrez par niveau et domaine. Les prix ne sont pas figés : vérifiez toujours la page officielle.</p><div class="checker"><select id="lv" aria-label="Niveau"><option value="">Tous niveaux</option>${["Débutant","Intermédiaire","Avancé"].map(x=>`<option>${x}</option>`).join("")}</select><select id="dm" aria-label="Domaine"><option value="">Tous domaines</option>${["Général","Pentest","SOC","GRC"].map(x=>`<option>${x}</option>`).join("")}</select></div><div class="grid" id="out"></div>`,
 roadmap:()=>`<h1>Cybersecurity Roadmap</h1><p class="lead">Un chemin général. Après les bases, choisissez une spécialisation au lieu d'essayer d'apprendre tout le domaine en même temps.</p><div class="roadmap">${D.roadmap.map((r,i)=>`<article class="road-step"><div class="step-num">${i+1}</div><div><h2>${r.n}</h2>${ul(r.items)}</div></article>`).join("")}</div><div class="panel"><h3>Spécialisations</h3><div class="grid">${["SOC / Blue Team","Pentest","Application Security","Cloud Security","DFIR","GRC"].map(x=>`<a class="mini-card" href="#/hack"><b>${x}</b><small>Voir les notions, outils et chemins de pratique associés.</small></a>`).join("")}</div></div><h2>Ressources de départ</h2>${D.resources.map(r=>`<div class="resource"><div><span class="tag">${r.cat}</span><h3>${r.n}</h3><p>${r.d}</p></div>${links([r])}</div>`).join("")}<h2>YouTube</h2><div class="grid">${D.youtube.map(y=>`<div class="panel"><h3>${y.n}</h3><p>${y.d}</p>${links([y])}</div>`).join("")}</div>`,
 learn:()=>`<h1>Fondamentaux</h1><p class="lead">Les concepts à connaître avant de se spécialiser : identité, cryptographie, réseau, défense et principes de sécurité.</p><div class="grid">${D.concepts.map(c=>`<article class="concept"><h3>${c.t}</h3><p>${c.d}</p></article>`).join("")}</div><div class="panel"><h3>Ordre conseillé</h3><p>Networking → systèmes → sécurité fondamentale → logs → outils → pratique → spécialisation.</p><a class="btn" href="#/roadmap">Voir la roadmap</a></div>`
};
const V={
 detect(){const show=i=>{const d=D.detect[i];$("#out").innerHTML=`<div class="cols"><div class="panel"><span class="eyebrow">INDICES</span><h3>Signes à vérifier</h3>${ul(d.signs)}</div><div class="do panel"><span class="eyebrow">ACTION</span><h3>Que faire maintenant</h3><ol>${d.now.map(x=>`<li>${esc(x)}</li>`).join("")}</ol></div></div><div class="panel"><h3>Outils associés</h3>${links(d.tools)}</div>`};chips(show)},
 protect(){const show=i=>{const a=D.assets[i],k="p_"+a.id;const draw=()=>{const d=store.get(k,[]),p=Math.round(d.length/a.m.length*100);$("#out").innerHTML=`<div class="panel"><div class="report-head"><h3>Protection : ${p} %</h3><span class="tag">${d.length}/${a.m.length} contrôles</span></div><div class="meter" role="progressbar" aria-valuenow="${p}" aria-valuemin="0" aria-valuemax="100"><i style="width:${p}%"></i></div>${a.m.map((m,j)=>`<label class="check"><input type="checkbox" data-j="${j}" ${d.includes(j)?"checked":""}><span>${esc(m[0])} ${m[1]?'<span class="tag">essentiel</span>':''}</span></label>`).join("")}</div>`;$("#out").querySelectorAll("input").forEach(c=>c.onchange=()=>{const s=new Set(store.get(k,[]));c.checked?s.add(+c.dataset.j):s.delete(+c.dataset.j);store.set(k,[...s]);draw()})};draw()};chips(show)},
 hack(){const show=i=>{const a=D.attacks[i];$("#out").innerHTML=`<div class="panel"><span class="eyebrow">FICHE ATTAQUE</span><h3>${a.t}</h3><p>${a.what}</p><h3>Chaîne simplifiée</h3><ol class="flow">${a.how.map(x=>`<li>${esc(x)}</li>`).join("")}</ol><div class="cols"><div><h3>Impact</h3><p>${a.impact}</p></div><div><h3>Détecter</h3><p>${a.detect}</p></div><div><h3>Prévenir</h3><p>${a.prevent}</p></div><div><h3>Pratique</h3><p>${a.lab}</p></div></div></div>`};chips(show)},
 tools(){const render=i=>{const f=D.finder[i],q=( $("#toolq")?.value||"").toLowerCase();const filtered=f.tools.filter(t=>(t.n+" "+f.k+" "+f.desc).toLowerCase().includes(q));$("#out").innerHTML=`<div class="panel"><span class="eyebrow">${esc(f.cat)}</span><h3>Analyser : ${esc(f.k)}</h3><p>${esc(f.desc)}</p>${filtered.length?filtered.map(t=>`<div class="tool-row"><div><b>${esc(t.n)}</b><small>Service externe</small></div><a class="btn btn-small" href="${esc(t.u)}" target="_blank" rel="noopener noreferrer">Ouvrir</a></div>`).join(""):"<p class='note'>Aucun outil ne correspond à cette recherche.</p>"}</div>`};chips(render);$("#toolq").oninput=()=>{const active=app.querySelector('.chip[aria-pressed="true"]');render(active?+active.dataset.i:0)}},
 certs(){const draw=()=>{const l=$("#lv").value,d=$("#dm").value,r=D.certs.filter(c=>(!l||c.lvl===l)&&(!d||c.dom===d));$("#out").innerHTML=r.length?r.map(c=>`<div class="panel"><div class="report-head"><h3>${esc(c.n)}</h3><span class="tag">${esc(c.lvl)}</span></div><p><span class="tag">${esc(c.dom)}</span> <span class="tag">${esc(c.px)}</span></p><p>${esc(c.who)}</p>${links([{n:"Site officiel",u:c.url}])}</div>`).join(""):"<p class='note'>Aucune certification ne correspond.</p>"};$("#lv").onchange=$("#dm").onchange=draw;draw()}
};
function route(){const p=(location.hash.replace("#/","")||"home").split("?")[0],page=R[p]?p:"home";app.innerHTML=R[page]();$("#nav").innerHTML=PAGES.map(x=>`<a href="#/${x[0]}" ${x[0]===page?'aria-current="page"':''}>${x[1]}</a>`).join("");if(page==="home"){$("#f").onsubmit=e=>{e.preventDefault();runCheck()}; if(window.CyberScene) window.CyberScene.mount("cyber-scene")}else V[page]&&V[page]();document.title=(page==="home"?"CyberHub":PAGES.find(x=>x[0]===page)?.[1])+" — CyberHub";scrollTo(0,0)}
addEventListener("hashchange",route);route();
